### ISSUE TITLE
在VideoCallActivity中引入的com.easemob.chat.EMChatManager为什么找不到

### ISSUE THREAD

**Issue by BBBOND** [easemob/sdkdemoapp3.0_android#109]
官网下的jar包是hyphenatechat——3.1.2.jar里的是 com.hyphenate.chat.EMChatManager  没有EMChatManager.getInstance()这个方法。。。这该怎么办？

**Comment by githubzhaoliang** [comment]
请使用sdk3.0 branch，3.x的sdk有一些改动，因此demo中也有相应的改动。
另外获取EMChatManager，可以用EMClient.getInstance().chatManager()，3.x版本统一了入口
