### ISSUE TITLE
Error:Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by micookie** [easemob/sdkdemoapp3.0_android#120]
导入项目提示：Error:Configuration with name 'default' not found.

**Comment by xygahs0801** [comment]
我也是

**Comment by micookie** [comment]
@xygahs0801 这个问题我搞定了，导入EaseUI项目，导入V4包。就好了。。但是有个新的问题缺com.easemob.util包

**Comment by good-devc** [comment]
@micookie 我也遇到这个问题，一个官方demo做成这样，我也是醉了。。。

**Comment by micookie** [comment]
@xygahs0801 @good-devc 
### 问题终于解决，最终原因是环信在github上提交的代码有问题。
### 下载：http://www.easemob.com/download 这个页面直接提供的SDK包

### http://downloads.easemob.com/downloads/android_IM_sdk_V3.1.2r2.zip

### 解压运行里边的example即可。


## 错误出处：对比github上和官方网站提供的压缩包，发现同一个类中代码的确不一样。
![2.jpg](https://ooo.0o0.ooo/2016/05/24/57448569df4e5.jpg)

**Comment by githubzhaoliang** [comment]
抱歉，你从github上取到的easeui是哪个branch， SDK3.x的需要使用sdk3.0的branch

**Comment by micookie** [comment]
sorry、我用的是master的。大概出错的都是跟我一样用的master的吧。
谢谢！

**Comment by qluojieq** [comment]
直接使用sdk中的demo靠谱的如micookie所说，

**Comment by weixx** [comment]
下载最新的SDK，解压出里边的Demo，导入Studio工程，还是报这个错啊！

**Comment by trywarrior** [comment]
我也是这个错误，环信真是牛逼

**Comment by zhanw** [comment]
release的时候可能忘注释 gradle文件，查看demo底下的settings.gradle及easeui下的build.gradle文件，把里面写着需要注释的地方加上//

settings.gradle中
//release时需要把下面的include相关的两行注释掉
//include ':hyphenatechatsdk'
//project(':hyphenatechatsdk').projectDir = new File('../emclient-android/hyphenatechatsdk')

以及easeui的build.gradle文件中
//release时需要把hyphenatechatsdk的依赖注释掉，sdk已经被打成jar包放在libs底下
//compile project(':hyphenatechatsdk')

**Comment by SearchSunny** [comment]
SDK\DEMO有点乱

**Comment by ZhaoMikeKe** [comment]
有点醉

**Comment by andyxiaoxi** [comment]
@micookie 大神，能否写个导入过程，我这直接的导入 eclipse,编译运行闪退，导入as,我只修改了gradle的版本，就各种报错
