### ISSUE TITLE
release_3.1.2 分支也是开发中的分支吗

### ISSUE THREAD

**Issue by tianshaokai** [easemob/sdkdemoapp3.0_android#131]

**Comment by githubzhaoliang** [comment]
是release之后的分支

**Comment by tianshaokai** [comment]
这sdk3.0 分支和release_3.1.2 有什么区别呢？我刚开始学习环信

**Comment by githubzhaoliang** [comment]
sdk3.0是开发分支，我们随时会提及更新，release 分支是经过一定的测试的，可以放心使用。
也欢迎contribute给我们的sdk3.0分支

**Comment by tianshaokai** [comment]
sdk3.0 分支我还以为是 环信的sdk 呢，其实也是demo 的代码吧
