### ISSUE TITLE
下载的SDK里包含example，可以正常运行，不要使用git上的代码

### ISSUE THREAD

**Issue by lichen228** [easemob/sdkdemoapp3.0_android#179]
自己踩过的坑，方便后人。即使把easesdk和easeui都从git上拉下来，并且把分支都切换到sdk3.0，或者都切换到release，build的时候依然会报default的问题。想快速使用example的朋友去使用吧：http://downloads.easemob.com/downloads/easemob-sdk-3.1.5.zip
解压后有个examples目录，可以正常使用

**Comment by jansonqiang** [comment]
真好人!!!手动点赞

**Comment by CeThum** [comment]
气死人了,我也是一直碰到build的时候依然会报default的问题,官方就不能把依赖弄好吗

**Comment by liuzheng9110** [comment]
登陆显示 使用uidemo中的账户登陆，这个帐号哪里找呢？

**Comment by githubzhaoliang** [comment]
账号可以自己注册

**Comment by AkashiWen** [comment]
被3.2.0坑过的来Mark一下。浪费我一天时间

**Comment by chengxueying** [comment]
3.2.0视频聊天链接不成功啊，有人遇到嘛

**Comment by miaosen** [comment]
遇到同样问题

**Comment by chengxueying** [comment]
3.2.1解决了网段不一样不能视频聊天的问题，新老版本不能链接成功

**Comment by ghost** [comment]
我会告诉你还是有一样的问题吗？

**Comment by tangjianye** [comment]
http://downloads.easemob.com/downloads/easemob-sdk-3.1.5.zip的examples里面的DEMO不是最新的3.x版本吧？

**Comment by githubzhaoliang** [comment]
@tangjianye 最新的版本已经是3.3.4了，参加http://docs.easemob.com/im/200androidclientintegration/160androidreleasenote
