### ISSUE TITLE
退出登录成功之后，还能获取到当前的用户名？代码如下，222能打印出最后一次登录的账号！按照我的理解，这个打印出来应该是空的

### ISSUE THREAD

**Issue by outhui** [easemob/sdkdemoapp3.0_android#263]
EMClient.getInstance().logout(true, new EMCallBack() {

            @Override
            public void onSuccess() {
                Log.e("111","退出成功");
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        String currentUser = EMClient.getInstance().getCurrentUser();
                        Log.e("222","currentUser:"+ currentUser);
                    }
                });
            }

            @Override
            public void onProgress(int progress, String status) {

            }

            @Override
            public void onError(int code, String message) {
                LogUtils.e("退出失败");
            }
        });

**Comment by githubzhaoliang** [comment]
已经修复，会包含在3.5.3版本中。
