### ISSUE TITLE
release包开启混淆发送图片会使App崩溃

### ISSUE THREAD

**Issue by zoujiacai** [easemob/sdkdemoapp3.0_android#374]
release包开启混淆发送图片会使App崩溃，发文本消息正常!

**Comment by zoujiacai** [comment]
debug包能正常发送图片，发文本！

**Comment by githubzhaoliang** [comment]
使用的android studio的版本是什么，之前有过一个客户有类似反馈，是3.4版本，后来升级到最新版本就可以了。

**Comment by zoujiacai** [comment]
我的Android studio 3.4.2 ！确认是开发工具的版本问题吗？

**Comment by zoujiacai** [comment]
感谢，还真是AS 3.4.2版本的问题，我升级到3.5.2就没问题了
