### ISSUE TITLE
求studio版本

### ISSUE THREAD

**Issue by liericiyan** [easemob/sdkdemoapp3.0_android#5]
希望能通过studio一步引用功能和布局的库，类似这样的引用compile 'com.ogaclejapan.smarttablayout:library:1.4.2@aar'
谢谢。

**Comment by liericiyan** [comment]
希望能通过studio一步引用功能和布局的库，类似这样的引用compile 'com.ogaclejapan.smarttablayout:library:1.4.2@aar'
谢谢。

**Comment by StormGens** [comment]
附议！

**Comment by Ydcool** [comment]
#### +1  

微信团队都早已放弃 ` eclipse + ant`  了~

**Comment by wangyisll** [comment]
附议！

**Comment by lzan13** [comment]
这是demo，不是一个库，studio可以直接导入，

**Comment by zhanw** [comment]
要是单纯做app的话，肯定用studio，还得考虑广大不用studio的开发者。
2.2.6中已添加相应gradle文件
